# Generated by Django 3.2.8 on 2021-10-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_rename_test_tweet_usertweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='userTweet',
            field=models.TextField(),
        ),
    ]
