# Generated by Django 3.2.8 on 2021-10-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_rename_body_tweet_contenttweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='contentTweet',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='userTweet',
            field=models.CharField(max_length=255),
        ),
    ]
